#
# Ranklist v0.2 Configuration File
# =====================================
#
# Please Don't use tabs in .yml file!
#  
# If for whatever reason you mess up this config just delete this config and
# the plugin will create you a new one!
#
# Please leave a comment or pm on bukkit dev if you have any trouble setting this up - TeOzFrAnK

#  NOTE: to add another rank simply remove the "#" and call it what you wish 
#  (no qoutes) then reload the server and try /ranklist to see the changes
#  also please do NOT add more than 10 ranks as this will not work as of yet
#  You can also change the server name to what ever you wish, enjoy! 

ranklist:
  servername: 'TeOzCommunity Minecraft Server'
  rank1: 'umember'
#  rank2: 'member'
#  rank3: 'donator'
#  rank4: 'donator+'
#  rank5: 'moderator'
#  rank6: 'moderator+'
#  rank7: 'admin'
#  rank8: 'admin+'
#  rank9: 'admin+++'
#  rank11: 'rank11'
#  rank12: 'rank12'
#  rank13: 'rank13'
#  rank14: 'rank14'
#  rank15: 'rank15'
#  rank16: 'rank16'
#  rank17: 'rank17'
#  rank18: 'rank18'
#  rank19: 'rank19'
#  rank20: 'rank20'

