#
# Ranklist v0.7+ Configuration File
# =====================================
#
# Please Don't use tabs in .yml file use spaces!
#  
# If for whatever reason you mess up this config just delete this config and
# the plugin will create you a new one!
#
# Please leave a comment or pm on bukkit dev if you have any trouble setting this up - TeOzFrAnK

#  NOTE: to add another rank simply go to a new line then type "- 'newrankhere' " without quotes
#  (no qoutes) then reload the plugin and try /ranklist to see the changes
#  You can also change the server name to what ever you wish, enjoy!
#
# default values
# checkforupdates: true  - should the plugin check for updates? (recommended)
# servername: 'my servername' - your server name
# ranks:
# - 'insert rank here'
# - 'insert another rank here'

ranklist:
  checkforupdates: true
  servername: '                  &bTeOzCommunity Minecraft Server      '
  description:
  - '              &6These are the rank(s) on our server     '
  - '            &aListed from the least powerful to the most     '
  ranks:
  - '&anoobie'
  - '&bmember'
  - '&ctrusted'
  - '&fv&ai&bp'
  - '&ddonator'
  - '&2submod'
  - '&3moderator'
  - '&2head &8moderator'

